trigger: none
# - main

schedules:
# Cron schedule - Every Day at 23:00 - same as '0 23 * * *'
- cron: '0 23 1-31 1-12 SUN-SAT'
  displayName: Daily Build
  branches:
    include:
    - main
  always: true

variables:  
  - template: vars.yml

stages:
  - stage: Build
    pool:
      vmImage: windows-latest
    variables:
      - name: 'PERSONALACCESSTOKEN'
        value: ${{ variables.personalAccessToken }}
      - name: 'BLOBAGETHRESHOLD'
        value: ${{ variables.blobAgeThreshold }}
    jobs:

# id1
    - job: ${{ variables.id1_name }}
      displayName: Powershell Script Execute
      variables:
        - name: 'SUBSCRIPTION'
          value: ${{ variables.id1_subscription }}
        - name: 'STORAGEACCOUNT'
          value: ${{ variables.id1_storageAccount }}
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ variables.id1_serviceConnection }}
            scriptType: filePath
            scriptPath: ./export-vnets.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true

# id2
    - job: ${{ variables.id2_name }}
      displayName: Powershell Script Execute
      variables:
        - name: 'SUBSCRIPTION'
          value: ${{ variables.id2_subscription }}
        - name: 'STORAGEACCOUNT'
          value: ${{ variables.id2_storageAccount }}
      steps:  
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ variables.id2_serviceConnection }}
            scriptType: filePath
            scriptPath: ./export-vnets.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true