trigger: none
# - main

variables:  
  - template: vars.yml

stages:
  - stage: Build
    pool:
      vmImage: windows-latest
    variables:
      - name: 'PERSONALACCESSTOKEN'
        value: ${{ variables.personalAccessToken }}
    jobs:

# id1
    - job: ${{ variables.id1_name }}
      displayName: Powershell Script Execute
      variables:
        - name: 'SUBSCRIPTION'
          value: ${{ variables.id1_subscription }}
        - name: 'STORAGEACCOUNT'
          value: ${{ variables.id1_storageAccount }}
        - name: 'DATEOFBACKUP'
          value: ${{ variables.id1_datOfBackup }}
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ variables.id1_serviceConnection }}
            scriptType: filePath
            scriptPath: ./restore-vnets.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true

# id2
    - job: ${{ variables.id2_name }}
      displayName: Powershell Script Execute
      variables:
        - name: 'SUBSCRIPTION'
          value: ${{ variables.id2_subscription }}
        - name: 'STORAGEACCOUNT'
          value: ${{ variables.id2_storageAccount }}
        - name: 'DATEOFBACKUP'
          value: ${{ variables.id2_datOfBackup }}
      steps:  
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: ${{ variables.id2_serviceConnection }}
            scriptType: filePath
            scriptPath: ./restore-vnets.ps1
            azurePowerShellVersion: latestVersion
            pwsh: true